export const publicationData = {
  idPub: "",
  idUser: "",
  direccion: "",
  title: "",
  temp1: "Temporada Alta",
  pric1: "",
  temp2: "Temporada Media",
  pric2: "",
  temp3: "Temporada Baja",
  pric3: "",
  balneario: "",
  cantHuespedes: "",
  tipoPropiedad: "",
  cantDormitorios: "",
  cantBanos: "",
  garaje: "",
  vistaAlMar: "",
  distanciaAlMar: "",
  dosPlazas: "",
  unaPlaza: "",
  sofaCama: "",
  colchon: "",
  cucheta: "",
  opcionesConfort: "",
  opcionesSeguridad: "",
  youtubeVideo: "",
  descripcionPropiedad: "",
  imagenesBase64: "",
};
